// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUocZhIJGIE4Ens7U9PFeW-ONtGk9nKg',
    appId: '1:587340109319:web:5a6ee6e6f04f16e8227ca2',
    messagingSenderId: '587340109319',
    projectId: 'venturenest-56da9',
    authDomain: 'venturenest-56da9.firebaseapp.com',
    storageBucket: 'venturenest-56da9.firebasestorage.app',
    measurementId: 'G-DMSSS2F6RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2u0zEYRaDcBJ-KFGj57JkGhXCv-5-bwQ',
    appId: '1:587340109319:android:cf768924657836b4227ca2',
    messagingSenderId: '587340109319',
    projectId: 'venturenest-56da9',
    storageBucket: 'venturenest-56da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ4fXfFBFdTLq_ZMRbgzzH2c8rqX0Gb4Q',
    appId: '1:587340109319:ios:c5ceae32f457a5f1227ca2',
    messagingSenderId: '587340109319',
    projectId: 'venturenest-56da9',
    storageBucket: 'venturenest-56da9.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ4fXfFBFdTLq_ZMRbgzzH2c8rqX0Gb4Q',
    appId: '1:587340109319:ios:c5ceae32f457a5f1227ca2',
    messagingSenderId: '587340109319',
    projectId: 'venturenest-56da9',
    storageBucket: 'venturenest-56da9.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUocZhIJGIE4Ens7U9PFeW-ONtGk9nKg',
    appId: '1:587340109319:web:db0720037e3285ce227ca2',
    messagingSenderId: '587340109319',
    projectId: 'venturenest-56da9',
    authDomain: 'venturenest-56da9.firebaseapp.com',
    storageBucket: 'venturenest-56da9.firebasestorage.app',
    measurementId: 'G-MLNYHD8QKL',
  );
}
